export const MAJOR_OPTIONS = [
    "Aerospace Engineering",
    "Applied Languages and Intercultural Studies",
    "Architecture",
    "Biochemistry",
    "Biology",
    "Biomedical Engineering",
    "Business Administration",
    "Chemical and Biomolecular Engineering",
    "Chemistry",
    "Civil Engineering",
    "Computational Media",
    "Computer Engineering",
    "Computer Science",
    "Earth and Atmospheric Sciences",
    "Economics",
    "Economics and International Affairs",
    "Electrical Engineering",
    "Environmental Engineering",
    "Global Economics and Modern Languages",
    "History, Technology, and Society",
    "Industrial Design",
    "Industrial Engineering",
    "International Affairs",
    "International Affairs and Modern Languages",
    "Literature, Media, and Communication",
    "Materials Science and Engineering",
    "Mathematics",
    "Mechanical Engineering",
    "Nuclear and Radiological Engineering",
    "Neuroscience",
    "Physics",
    "Psychology",
    "Public Policy",
];

export const EXPOSURE_OPTIONS = [
    "Friend or relative in GT AKPsi",
    "Friend or relative NOT in GT AKPsi",
    "Instagram Account",
    "Instagram Ad",
    "GT 1000/2000 Advertisement",
    "Email Newsletter",
    "Canvas Announcement",
    "TikTok",
    "LinkedIn",
    "Reddit",
    "Email",
    "Flyer Found on Campus",
    "Via Another Organization",
    "AKPsi Website/Online Search",
    "Virtual Information Session",
    "Resume Blitz",
    "Fall Org Fair",
    "Interest Night",
    "Scheller Org Fair",
    "Tabling Event",
];
