export const EXPOSURE_OPTIONS = [
    "Friend or relative in GT AKPsi",
    "Friend or relative NOT in GT AKPsi",
    "Instagram Account",
    "Instagram Ad",
    "GT 1000/2000 Advertisement",
    "Email Newsletter",
    "Canvas Announcement",
    "TikTok",
    "LinkedIn",
    "Reddit",
    "Email",
    "Flyer Found on Campus",
    "Via Another Organization",
    "AKPsi Website/Online Search",
    "Virtual Information Session",
    "Resume Blitz",
    "Fall Org Fair",
    "Interest Night",
    "Scheller Org Fair",
    "Tabling Event",
];
